# Generated by Django 5.1.5 on 2025-05-30 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('gst_no', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlassSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Techno.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_charges', to='Techno.glasssummary')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=10)),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('area', models.FloatField()),
                ('rate', models.FloatField()),
                ('amount', models.FloatField()),
                ('shape', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Techno.customer')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='Techno.glasssummary')),
            ],
        ),
    ]
