# Generated by Django 5.1.5 on 2025-05-30 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Techno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracharge',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Techno.customer'),
            preserve_default=False,
        ),
    ]
