# Generated by Django 5.1.5 on 2025-05-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Techno', '0003_alter_customer_gst_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gst_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
