# Generated by Django 5.1.5 on 2025-06-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Techno', '0004_alter_customer_gst_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='glasssummary',
            name='pi_no',
            field=models.PositiveIntegerField(default=200),
            preserve_default=False,
        ),
    ]
