# Generated by Django 5.1.5 on 2025-06-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Techno', '0005_glasssummary_pi_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='salesman',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
