# Generated by Django 5.1.5 on 2025-06-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Techno', '0006_measurement_salesman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='salesman',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
